[2024-07-16T05:54:40.606+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T05:54:40.659+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_batch.run_query6 manual__2024-07-16T05:53:33.394947+00:00 [queued]>
[2024-07-16T05:54:40.703+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_batch.run_query6 manual__2024-07-16T05:53:33.394947+00:00 [queued]>
[2024-07-16T05:54:40.706+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-16T05:54:40.722+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_query6> on 2024-07-16 05:53:33.394947+00:00
[2024-07-16T05:54:40.731+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1582) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-16T05:54:40.731+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_batch', 'run_query6', 'manual__2024-07-16T05:53:33.394947+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/batch_dag.py', '--cfg-path', '/tmp/tmpu6fbrud4']
[2024-07-16T05:54:40.734+0000] {standard_task_runner.py:63} INFO - Started process 1611 to run task
[2024-07-16T05:54:40.737+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask run_query6
[2024-07-16T05:54:40.792+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_batch.run_query6 manual__2024-07-16T05:53:33.394947+00:00 [running]> on host 6f712de23803
[2024-07-16T05:54:40.887+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='angel' AIRFLOW_CTX_DAG_ID='daily_batch' AIRFLOW_CTX_TASK_ID='run_query6' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T05:53:33.394947+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T05:53:33.394947+00:00'
[2024-07-16T05:54:40.889+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T05:54:40.907+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-16T05:54:41.192+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T05:54:41.194+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/batch_dag.py", line 61, in run_query_and_save_to_csv
    df.to_csv(f'/path/to/save/directory/{query_id}.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/path/to/save/directory'
[2024-07-16T05:54:41.219+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=daily_batch, task_id=run_query6, run_id=manual__2024-07-16T05:53:33.394947+00:00, execution_date=20240716T055333, start_date=20240716T055440, end_date=20240716T055441
[2024-07-16T05:54:41.245+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 37 for task run_query6 (Cannot save file into a non-existent directory: '/path/to/save/directory'; 1611)
[2024-07-16T05:54:41.256+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-16T05:54:41.274+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T05:54:41.278+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
