[2024-07-14T20:35:46.314+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T20:35:46.331+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T20:00:00+00:00 [queued]>
[2024-07-14T20:35:46.335+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T20:00:00+00:00 [queued]>
[2024-07-14T20:35:46.335+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T20:35:46.341+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 20:00:00+00:00
[2024-07-14T20:35:46.346+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2351) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T20:35:46.346+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T20:00:00+00:00', '--job-id', '1071', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpzy5tap2k']
[2024-07-14T20:35:46.347+0000] {standard_task_runner.py:63} INFO - Started process 2355 to run task
[2024-07-14T20:35:46.347+0000] {standard_task_runner.py:91} INFO - Job 1071: Subtask save_and_flush_task
[2024-07-14T20:35:46.374+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T20:00:00+00:00 [running]> on host 77caf7e4b282
[2024-07-14T20:35:46.426+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T20:00:00+00:00'
[2024-07-14T20:35:46.428+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T20:35:46.434+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T20:35:46.435+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T20:35:46.441+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T20:00:00+00:00, execution_date=20240714T200000, start_date=20240714T203546, end_date=20240714T203546
[2024-07-14T20:35:46.486+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T20:35:46.496+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T20:35:46.497+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-15T06:37:54.979+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T06:37:55.008+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T20:00:00+00:00 [queued]>
[2024-07-15T06:37:55.019+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T20:00:00+00:00 [queued]>
[2024-07-15T06:37:55.023+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T06:37:55.037+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 20:00:00+00:00
[2024-07-15T06:37:55.051+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4058) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T06:37:55.054+0000] {standard_task_runner.py:63} INFO - Started process 4065 to run task
[2024-07-15T06:37:55.053+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T20:00:00+00:00', '--job-id', '708', '--raw', '--subdir', 'DAGS_FOLDER/et_dag.py', '--cfg-path', '/tmp/tmpey7ym7pm']
[2024-07-15T06:37:55.060+0000] {standard_task_runner.py:91} INFO - Job 708: Subtask save_and_flush_task
[2024-07-15T06:37:55.116+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T20:00:00+00:00 [running]> on host 52e7a9c3d832
[2024-07-15T06:37:55.205+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T20:00:00+00:00'
[2024-07-15T06:37:55.207+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T06:37:55.216+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T06:37:55.217+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_dag.py", line 38, in trigger_save_and_flush
    logging('Invoking method to save data from records')
TypeError: 'module' object is not callable
[2024-07-15T06:37:55.232+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T20:00:00+00:00, execution_date=20240714T200000, start_date=20240715T063755, end_date=20240715T063755
[2024-07-15T06:37:55.246+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 708 for task save_and_flush_task ('module' object is not callable; 4065)
[2024-07-15T06:37:55.282+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T06:37:55.292+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
